### ISSUE TITLE
COMMENT - GET BY POSTID

### ISSUE THREAD

**Issue by yarelismartin** [ursapictura/Rare-BE#6]
### **Description**
Implement the GET BY POSTID route for the COMMENT entity.
- **Entity**: COMMENT
- **Action**: GET BY POSTID

---
### **Task Breakdown**
- [x] Include endpoint in its API file within the APIs folder
- [x] Define the route path.
- [x] Handle request validation and data persistence.
- [ ] Implement error handling and appropriate status codes.
- [ ] Test on Swagger

---
### **Request**
- **HTTP Method**: GET BY POSTID
- **Path**: `/api/comments/posts/{postid}`

### **Response**
- **Status Code**:
- **Body**:
```
{
id 
author id 
author {
    first name 
    last name 
    profile img
    }, 
post id,
content
}
 ```
